name: 'openpilot env setup'

inputs:
  is_retried:
    description: 'A mock param that asserts that we use the setup-with-retry instead of this action directly'
    required: false
    default: 'false'

env:
  DEBIAN_FRONTEND: noninteractive
  OPENCL_DOWNLOAD_PATH: /tmp/opencl-downloads

runs:
  using: "composite"
  steps:
    - name: Enforce usage through setup-with-retry
      shell: bash
      if: ${{ inputs.is_retried == 'false' }}
      run: |
        echo "You should not run this action directly. Use setup-with-retry instead"
        exit 1

    - name: Fail on GitHub retry attempt
      shell: bash
      run: |
        if [ "${{ github.run_attempt }}" -gt 1 ]; then
          echo -e "\033[0;31mRetries not allowed! Fix the flaky test!\033[0m"
          exit 1
        fi

    - name: Git LFS Pull
      shell: bash
      run: git lfs pull

    - name: Generate scons cache key
      id: date
      shell: bash
      run: echo "CACHE_COMMIT_DATE=$(git log -1 --pretty='format:%cd' --date=format:'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV

    - name: Restore scons cache
      uses: ./.github/actions/auto-cache
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
        restore-keys: |
          scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}
          scons-${{ runner.arch }}

    - name: Cache apt packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('.github/list_of_apt_packages.txt') }}
        restore-keys: ${{ runner.os }}-apt-

    - name: Install apt packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          tzdata locales ssh pulseaudio xvfb x11-xserver-utils gnome-screenshot python3-tk python3-dev \
          apt-utils alien unzip tar curl xz-utils dbus gcc-arm-none-eabi tmux vim libx11-6 wget \
          ca-certificates clang build-essential liblzma-dev capnproto libcapnp-dev libcurl4-openssl-dev \
          git git-lfs ffmpeg libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libavfilter-dev \
          libbz2-dev libeigen3-dev libffi-dev libglew-dev libgles2-mesa-dev libglfw3-dev libglib2.0-0 \
          libjpeg-dev libqt5charts5-dev libncurses5-dev libssl-dev libusb-1.0-0-dev libzmq3-dev libzstd-dev \
          libsqlite3-dev libsystemd-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev portaudio19-dev \
          qttools5-dev-tools libqt5svg5-dev libqt5serialbus5-dev libqt5x11extras5-dev libqt5opengl5-dev \
          g++-12 qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools python3-venv
        sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && sudo locale-gen en_US.UTF-8
        sudo rm -rf /var/lib/apt/lists/*

    - name: Install udev rules
      shell: bash
      run: |
        echo 'Installing udev rules...'
        echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="3801", ATTRS{idProduct}=="ddcf", MODE="0666"' | sudo tee /etc/udev/rules.d/12-panda_jungle.rules
        echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", MODE="0666"' | sudo tee /etc/udev/rules.d/11-panda.rules
        sudo udevadm control --reload-rules && sudo udevadm trigger || true

    - name: Cache OpenCL downloads
      uses: actions/cache@v4
      with:
        path: ${{ env.OPENCL_DOWNLOAD_PATH }}
        key: opencl-intel-tbb-v1
        restore-keys: opencl-

    - name: Install OpenCL + TBB
      shell: bash
      run: |
        mkdir -p $OPENCL_DOWNLOAD_PATH && cd $OPENCL_DOWNLOAD_PATH
        wget -nc https://github.com/intel/llvm/releases/download/2024-WW14/oclcpuexp-2024.17.3.0.09_rel.tar.gz
        wget -nc https://github.com/oneapi-src/oneTBB/releases/download/v2021.12.0/oneapi-tbb-2021.12.0-lin.tgz
        sudo mkdir -p /opt/intel/oclcpuexp
        sudo tar -zxvf oclcpuexp-*.tar.gz -C /opt/intel/oclcpuexp --strip-components=1
        sudo mkdir -p /opt/intel/tbb
        sudo tar -zxvf oneapi-tbb-*.tgz -C /opt/intel/tbb --strip-components=1
        echo /opt/intel/oclcpuexp/x64/libintelocl.so | sudo tee /etc/OpenCL/vendors/intel_expcpu.icd
        sudo ldconfig

    - name: Cache Python venv + uv
      uses: actions/cache@v4
      with:
        path: |
          .venv
          ~/.cache/uv
        key: ${{ runner.os }}-python-${{ hashFiles('uv.lock') }}
        restore-keys: ${{ runner.os }}-python-

    - name: Setup Python env
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.local/bin:$PATH"
        python3 -m venv .venv
        source .venv/bin/activate
        uv sync --frozen --all-extras uv.lock
        echo "PYTHONPATH=${GITHUB_WORKSPACE}" > .env
        echo ".venv/bin" >> $GITHUB_PATH
